---
title: 'COVID-19 : worldwide interacive map'
author: "Firas Ismail"
date: "08/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE,message = FALSE)
```

### Cases and deaths by country up to `r Sys.Date()-1`  
This map can be automatically updated by re-knitting the *map.RMD* file everyday.

```{r, echo=FALSE }
library(leaflet)
library(openxlsx)
library(dplyr)

date<-Sys.Date()-1
URL<-paste0("http://www.ecdc.europa.eu/sites/default/files/documents/COVID-19-geographic-disbtribution-worldwide-",date,".xlsx")
filename<-paste0("data\\covid_",date,".xlsx")
if (!file.exists(filename))
    download.file(URL,
                  destfile=filename,
                  mode="wb")


covid<- read.xlsx(filename,sheet=1)
countries<-read.csv("data\\countries.csv")
codes<-read.csv("data\\codes.csv")

df<-group_by(covid,countryCode=countryterritoryCode) %>% summarise(cases=sum(cases),deaths=sum(deaths),population=mean(popData2018))

codes<-codes[,c(2,3)]

combined<-merge(codes,countries,by.x="Alpha.2.code",by.y="country")

df<-merge(df,combined[,c(2:5)],by.x="countryCode",by.y="Alpha.3.code")



map<-df%>% 
    leaflet() %>% 
    addTiles() %>% 
    addCircles(lng=df$longitude,lat=df$latitude, weight=1,radius=sqrt(df$cases)*1500,label = paste0("Cases in ",df$name," : ",format(df$cases, big.mark=",")),color = "blue",labelOptions = labelOptions(interactive=TRUE,textsize="17px")) %>% 
    addCircles(lng=df$longitude,lat=df$latitude, weight=1,radius=sqrt(df$deaths)*1500,label = paste0("Deaths in ",df$name," : ",format(df$deaths, big.mark=",")),color = "red",labelOptions = labelOptions(interactive=TRUE,textsize="17px"))  
    
map
```

### Resources:     
This data was obtained from the [*European Centre for Disease Prevention and Control Wibsite(ECDC)*](https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide)      

### Source code:     
Full source code with the necessary data files can be found  [here](https://github.com/fyras1/COVID-19-worldwide-Interactive-map)